In [0]:
import pandas as pd
import numpy as np

In [0]:
df=pd.read_csv('/content/mushrooms.csv')

In [3]:
df.head()

class cap-shape cap-surface  ... spore-print-color population habitat
0     p         x           s  ...                 k          s       u
1     e         x           s  ...                 n          n       g
2     e         b           s  ...                 n          n       m
3     p         x           y  ...                 k          s       u
4     e         x           s  ...                 n          a       g

[5 rows x 23 columns]

In [4]:
df.describe()

class cap-shape cap-surface  ... spore-print-color population habitat
count   8124      8124        8124  ...              8124       8124    8124
unique     2         6           4  ...                 9          6       7
top        e         x           y  ...                 w          v       d
freq    4208      3656        3244  ...              2388       4040    3148

[4 rows x 23 columns]

In [0]:
features=df.iloc[:,1:]

In [7]:
features.head()

cap-shape cap-surface cap-color  ... spore-print-color population habitat
0         x           s         n  ...                 k          s       u
1         x           s         y  ...                 n          n       g
2         b           s         w  ...                 n          n       m
3         x           y         w  ...                 k          s       u
4         x           s         g  ...                 n          a       g

[5 rows x 22 columns]

In [0]:
label=df.iloc[:,:1]

In [9]:
label.head()

class
0     p
1     e
2     e
3     p
4     e

In [0]:
def encode(x):
  from sklearn.preprocessing import LabelEncoder
  l=LabelEncoder()
  x=l.fit_transform(x)
  return x

In [11]:
print(encode(features['cap-shape']))

[5 5 0 ... 2 3 5]


In [0]:
cols=features.columns

In [0]:
cols=cols.tolist()

In [15]:
cols

['cap-shape',
 'cap-surface',
 'cap-color',
 'bruises',
 'odor',
 'gill-attachment',
 'gill-spacing',
 'gill-size',
 'gill-color',
 'stalk-shape',
 'stalk-root',
 'stalk-surface-above-ring',
 'stalk-surface-below-ring',
 'stalk-color-above-ring',
 'stalk-color-below-ring',
 'veil-type',
 'veil-color',
 'ring-number',
 'ring-type',
 'spore-print-color',
 'population',
 'habitat']

In [0]:
dic={}
for s in cols:
  dic[s]=encode(features[s])


In [17]:
dic

{'bruises': array([1, 1, 1, ..., 0, 0, 0]),
 'cap-color': array([4, 9, 8, ..., 4, 4, 4]),
 'cap-shape': array([5, 5, 0, ..., 2, 3, 5]),
 'cap-surface': array([2, 2, 2, ..., 2, 3, 2]),
 'gill-attachment': array([1, 1, 1, ..., 0, 1, 0]),
 'gill-color': array([ 4,  4,  5, ...,  5,  0, 11]),
 'gill-size': array([1, 0, 0, ..., 0, 1, 0]),
 'gill-spacing': array([0, 0, 0, ..., 0, 0, 0]),
 'habitat': array([5, 1, 3, ..., 2, 2, 2]),
 'odor': array([6, 0, 3, ..., 5, 8, 5]),
 'population': array([3, 2, 2, ..., 1, 4, 1]),
 'ring-number': array([1, 1, 1, ..., 1, 1, 1]),
 'ring-type': array([4, 4, 4, ..., 4, 0, 4]),
 'spore-print-color': array([2, 3, 3, ..., 0, 7, 4]),
 'stalk-color-above-ring': array([7, 7, 7, ..., 5, 7, 5]),
 'stalk-color-below-ring': array([7, 7, 7, ..., 5, 7, 5]),
 'stalk-root': array([3, 2, 2, ..., 0, 0, 0]),
 'stalk-shape': array([0, 0, 0, ..., 0, 1, 0]),
 'stalk-surface-above-ring': array([2, 2, 2, ..., 2, 2, 2]),
 'stalk-surface-below-ring': array([2, 2, 2, ..., 2, 1, 2]),
 

In [0]:
ff=pd.DataFrame(dic)

In [19]:
ff

cap-shape  cap-surface  cap-color  ...  spore-print-color  population  habitat
0             5            2          4  ...                  2           3        5
1             5            2          9  ...                  3           2        1
2             0            2          8  ...                  3           2        3
3             5            3          8  ...                  2           3        5
4             5            2          3  ...                  3           0        1
...         ...          ...        ...  ...                ...         ...      ...
8119          3            2          4  ...                  0           1        2
8120          5            2          4  ...                  0           4        2
8121          2            2          4  ...                  0           1        2
8122          3            3          4  ...                  7           4        2
8123          5            2          4  ...                  4           1        2

[8124 rows x 22 columns]

In [0]:
from sklearn.preprocessing import StandardScaler

In [0]:
sc=StandardScaler()

In [0]:
ff=sc.fit_transform(ff)

In [23]:
ff

array([[ 1.02971224,  0.14012794, -0.19824983, ..., -0.67019486,
        -0.5143892 ,  2.03002809],
       [ 1.02971224,  0.14012794,  1.76587407, ..., -0.2504706 ,
        -1.31310821, -0.29572966],
       [-2.08704716,  0.14012794,  1.37304929, ..., -0.2504706 ,
        -1.31310821,  0.86714922],
       ...,
       [-0.8403434 ,  0.14012794, -0.19824983, ..., -1.50964337,
        -2.11182722,  0.28570978],
       [-0.21699152,  0.95327039, -0.19824983, ...,  1.42842641,
         0.28432981,  0.28570978],
       [ 1.02971224,  0.14012794, -0.19824983, ...,  0.16925365,
        -2.11182722,  0.28570978]])

In [25]:
label['class']=encode(label['class'])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [26]:
label

class
0         1
1         0
2         0
3         1
4         0
...     ...
8119      0
8120      0
8121      0
8122      1
8123      0

[8124 rows x 1 columns]

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
x_train,x_test,y_train,y_test=train_test_split(ff,label,test_size=0.2,shuffle=True)

In [36]:
y_train

class
5444      1
7996      0
4598      1
5751      1
7346      0
...     ...
3408      0
4792      1
5378      0
2864      0
7062      1

[6499 rows x 1 columns]

In [0]:
from sklearn.neighbors import KNeighborsClassifier

In [0]:
kn=KNeighborsClassifier(n_neighbors=3)

In [39]:
kn.fit(x_train,y_train)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  """Entry point for launching an IPython kernel.


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [40]:
kn.score(x_test,y_test)

1.0

In [0]:
from sklearn.svm import SVC

In [0]:
sc=SVC()

In [45]:
sc.fit(x_train,y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [46]:
sc.score(x_test,y_test)

1.0

In [0]:
from sklearn.tree import DecisionTreeClassifier

In [0]:
d=DecisionTreeClassifier()

In [51]:
d.fit(x_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [52]:
d.score(x_test,y_test)

1.0

In [0]:
y_pred=d.predict(x_test)

In [0]:
from sklearn.metrics import classification_report,confusion_matrix

In [58]:
classification_report(y_pred,y_test)

'              precision    recall  f1-score   support\n\n           0       1.00      1.00      1.00       840\n           1       1.00      1.00      1.00       785\n\n    accuracy                           1.00      1625\n   macro avg       1.00      1.00      1.00      1625\nweighted avg       1.00      1.00      1.00      1625\n'

In [0]:
from sklearn.ensemble import RandomForestClassifier

In [0]:
rd=RandomForestClassifier(n_estimators=50)

In [62]:
rd.fit(x_train,y_train)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=50,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [63]:
rd.score(x_test,y_test)

1.0

In [0]:
pred=rd.predict(x_test)

In [0]:
cm=confusion_matrix(y_test,pred)

In [67]:
cm

array([[840,   0],
       [  0, 785]])

In [0]:
from sklearn.linear_model import LogisticRegression

In [0]:
log=LogisticRegression()

In [73]:
log.fit(x_train,y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [74]:
log.score(x_test,y_test)

0.9538461538461539

In [0]:
from sklearn.model_selection import cross_val_score

In [77]:
scores=cross_val_score(log,ff,label,verbose=1)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d ar

In [78]:
scores

array([0.67876923, 0.98215385, 0.87569231, 0.99815385, 0.61576355])

In [0]:
from sklearn.model_selection import GridSearchCV

In [0]:
gd=GridSearchCV(log,{'penalty':['l1','l2']})

In [82]:
gd.fit(x_train,y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
ValueError: Solver lbfgs supports only 'l2' or 'none' penalties, got l1 penalty.

  FitFailedWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please ch

GridSearchCV(cv=None, error_score=nan,
             estimator=LogisticRegression(C=1.0, class_weight=None, dual=False,
                                          fit_intercept=True,
                                          intercept_scaling=1, l1_ratio=None,
                                          max_iter=100, multi_class='auto',
                                          n_jobs=None, penalty='l2',
                                          random_state=None, solver='lbfgs',
                                          tol=0.0001, verbose=0,
                                          warm_start=False),
             iid='deprecated', n_jobs=None,
             param_grid={'penalty': ['l1', 'l2']}, pre_dispatch='2*n_jobs',
             refit=True, return_train_score=False, scoring=None, verbose=0)

In [83]:
gd.score(x_test,y_test)

0.9538461538461539